pipeline{
    agent any
stages{
    stage('build'){
        agent{
            docker{
            image 'python:2.7.16-slim'
            }
         }
         when{
             changeset "**/vote/**"
         }
        steps{
            echo 'Compiling vote app...'
            dir('vote'){
                sh 'pip install -r requirement.txt'
            }
        }
    }

    stage('test'){
        agent{
            docker{
            image 'python:2.7.16-slim'
            }
         }
         when{
            branch 'master'
            changeset "**/vote/**"
        }
        steps{
            echo 'Running Unit Tests vote app...'
            dir('vote'){
                sh 'nosetest -v'
            }
        }
    }

    stage('docker-package'){
        agent any
        when{
            branch 'master'
            changeset "**/vote/**"
        }
        steps{
            echo 'Packaging vote with docker'
            script{
                docker.withRegistry('https://index.docker.io/v1/','dockerlogin'){
                    def voteImage = docker.build("lruizhpe/vote:v${env.BUILD_ID}","./vote")
                    voteImage.push()
                }
            }
        }
    }
}

}

